---
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - name: Verifique se o Nginx está rodando
      command: service nginx status
      args:
        warn: false
      changed_when: false

    - name: Verifique se o Nginx está escutando na porta 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: Verifique se o Apache2 está rodando
      command: service apache2 status
      args:
        warn: false
      changed_when: false

    - name: Verifique se o Apache2 está escutando na porta 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: Verifique se o MySQL está rodando
      command: service mysql status
      args:
        warn: false
      changed_when: false

    - name: Verifique se o MySQL está escutando na porta 3306
      wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 timeout=1