---
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - name: Verifique se o Nginx está rodando
      command: service nginx status

    - name: Verifique se o Nginx está escutando na porta 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: Verifique se o Apache2 está rodando
      command: service apache2 status

    - name: Verifique se o Apache2 está escutando na porta 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: Verifique se o MySQL está rodando
      command: service mysql status

    - name: Verifique se o MySQL está escutando na porta 3306
      wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 timeout=1

- hosts: control
  gather_facts: no
  tasks:
    - name: Verificar a resposta do índice de ponta a ponta
      uri: url=http://{{item}} return_content=yes
      with_items: groups.loadbalancer
      register: lb_index

    - fail: msg="Índice falhou ao retornar conteúdo"
      when: "'Hello, from Ansible' not in item.content"
      with_items: "{{lb_index.results}}"

    - name: Verificar a resposta do DB de ponta a ponta
      uri: url=http://{{item}}/db return_content=yes
      with_items: groups.loadbalancer
      register: lb_db

    - fail: msg="DB falhou ao retornar conteúdo"
      when: "'Banco de Dados Conectado de' not in item.content"
      with_items: "{{lb_db.results}}"

- hosts: loadbalancer
  tasks:
    - name: verificar resposta do índice de backend
      uri: url=http://{{item}} return_content=yes
      with_items: groups.webserver
      register: app_index

    - fail: msg="Índice falhou ao retornar conteúdo"
      when: "'Hello, from sunny {{item.item}}!' not in item.content"
      with_items: "{{app_index.results}}"

    - name: verificar resposta do backend db
      uri: url=http://{{item}}/db return_content=yes
      with_items: groups.webserver
      register: app_db

    - fail: msg="DB não conseguiu retornar o conteúdo"
      when: "'Banco de Dados Conectado de {{item.item}}!' not in item.content"
      with_items: "{{app_db.results}}"