---
- name: Família Debian instala o rkHunter, o CheckrootKit e Clamv Antivirus
  package:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - clamav
    - rkhunter
    - chkrootkit
    - clamav-daemon
    - at
  when: ansible_os_family == 'Debian'

- name: El6 / 7 instalar o rkHunter, CheckrootKit, Clamv Antivirus
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - clamav
    - rkhunter
    - at
  when: ansible_os_family == 'RedHat'

# Executar e verificar os resultados
- name: Execute Clamscan Fire e Forgot
  command: clamscan -i /tmp
  async: 45
  poll: 0
  register: clamscan

#- name: CLAMV fire e exibir resultados
#  async_status: jid={{ clamscan.ansible_job_id }}
#  register: job_result
#  until: job_result.finished
#  retries: 30
#- debug: var=job_result.stdout_lines

# Programar o CLam Scan e Enviar EMails
- name: Executar o Clamv uma vez por semana
  at:
    command: "clamscan -i /tmp | mail devops@gmail.com"
    count: 1
    units: weeks