---
  - name: Instalando Apache2 e componentes do webserver
    apt:
      name: [apache2, libapache2-mod-wsgi]
      state: latest

  - name: Garantir que o mod_wsgi esteja ativado
    apache2_module: state=present name=wsgi
    notify: restart apache2

  - name: Desativar o site padrão do apache
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
    notify: restart apache2

  - name: Iniciando Apache2
    service: name=apache2 state=started enabled=yes